language: python
sudo: true
python:
- '3.2_with_system_site_packages'
cache:
  directories:
  - "$HOME/.cache/pip"
  - ".tox"

before_install:
- sudo apt-get update
- sudo apt-get install -qq python3-gi gir1.2-glib-2.0
- sudo apt-get install libcairo2-dev libgirepository1.0-dev libglib2.0-dev
- pip install pygobject
- pip install pydbus
install:
- pip install tox
script: tox --recreate
deploy:
  provider: pypi
  user: peplin
  password:
    secure: dLMAsEz0Suzhq4eOMZ4t05wwI6GrwTvAju9cN28dc1uivSrvqga4lTSajQubVQ0gRIJZYg/WZZxXG9hHg9VMWHrdYNY/va9V8lz9nDCLPjg2xadOQPj6A5CqyD+rxK7tZvwfKPDIoUWDfrMIFVEGFptCCgePBuEiE5MhL9Bqxes=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: peplin/pygatt
